force-app/main/default/objects/ViSearchR_Settings__c/ViSearchR_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>ViSearchR Settings</description>
    <label>ViSearchR Settings</label>
</CustomObject>

force-app/main/default/objects/ViSearchR_Settings__c/fields/API_Base_URL__c.field-meta.xml
<CustomField>
    <fullName>API_Base_URL__c</fullName>
    <label>API Base URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/ViSearchR_Settings__c/fields/API_Keys__c.field-meta.xml
<CustomField>
    <fullName>API_Keys__c</fullName>
    <label>API Keys</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ViSearchR_Settings.cls
public with sharing class ViSearchR_Settings {
	public static final String API_ENDPOINT;
    public static final String API_KEYS;
    public static final Id USER_ID;
    public static final ViSearchR_Settings__c SETTINGS;
    static {
        try {
            Id profileId = UserInfo.getProfileId();
            ViSearchR_Settings__c setting = ViSearchR_Settings__c.getInstance(profileId);
            
            if(setting.Id == null) {
                setting = ViSearchR_Settings__c.getOrgDefaults();
            }
            
            if(setting.Id == null) {
                throw new ViSearchR_SettingsException('Missing Oauth settings.');
            }
            
            USER_ID = UserInfo.getUserId();
            SETTINGS = setting;
            
            if(setting.API_Base_URL__c != null){
                API_ENDPOINT = setting.API_Base_URL__c.removeEnd('/');
            }
            
            if(setting.API_Keys__c != null){
                API_KEYS = setting.API_Keys__c;
            }
        } catch(Exception e) {
            throw new ViSearchR_SettingsException('Unabled to initialize Oauth Settings: ' + e.getMessage());
        }
    }
    public class ViSearchR_SettingsException extends Exception {}
}